name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '41 10 * * *'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          expire-in: 7days
